### ISSUE TITLE
To do: fix step 18

### ISSUE THREAD

**Issue by nlhomme** [nlhomme/pytgvoip#3]
```
Step 18/28 : RUN python3 setup.py install
 ---> Running in 7a050d57ff14
running install
running build
running build_ext
building 'tgvoip' extension
creating build
creating build/temp.linux-x86_64-3.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c tgvoip.cpp -o build/temp.linux-x86_64-3.7/tgvoip.o
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                
The command '/bin/sh -c python3 setup.py install' returned a non-zero code: 1   
```

**Comment by Baptiste-Leterrier** [comment]
Added python3-dev to dockerfile in branch patch-issue-step-18.

Now error read: 

`The command '/bin/sh -c git checkout v1.6.0 && rm -rf build && mkdir build && cd build && export CXXFLAGS="-stdlib=libc++" && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib .. && cmake --build . --target install && cd .. && cd .. && ls -l td/tdlib' returned a non-zero code: 130`

**Comment by Baptiste-Leterrier** [comment]
Issue is fixed with commit https://github.com/nlhomme/pytgvoip/commit/e3f77c5f5f6cebeb804bf04967f723713a60d44b
