### ISSUE TITLE
Error in container when python code is executed

### ISSUE THREAD

**Issue by Baptiste-Leterrier** [nlhomme/pytgvoip#5]
Return is printed when runing the container with 

# docker run -it nlhomme/pytgvoip:latest

Traceback (most recent call last):
  File "/root/tgcall.py", line 10, in <module>
    from telegram.client import Telegram
ModuleNotFoundError: No module named 'telegram'

**Comment by Baptiste-Leterrier** [comment]
I'm trying to recompile libtgvoip to include it to Docker and get the lib

**Comment by nlhomme** [comment]
> Return is printed when runing the container with 
> 
> 
> 
> # docker run -it nlhomme/pytgvoip:latest
> 
> 
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/root/tgcall.py", line 10, in <module>
> 
>     from telegram.client import Telegram
> 
> ModuleNotFoundError: No module named 'telegram'

We should see [this](https://stackoverflow.com/questions/45382698/although-i-install-python-telegram-bot-error-of-no-module-named-telegram)

**Comment by nlhomme** [comment]
> > Return is printed when runing the container with 
> > 
> > 
> > 
> > # docker run -it nlhomme/pytgvoip:latest
> > 
> > 
> > 
> > 
> > 
> > Traceback (most recent call last):
> > 
> >   File "/root/tgcall.py", line 10, in <module>
> > 
> >     from telegram.client import Telegram
> > 
> > ModuleNotFoundError: No module named 'telegram'
> 
> We should see [this](https://stackoverflow.com/questions/45382698/although-i-install-python-telegram-bot-error-of-no-module-named-telegram)
> 

I think the solution is
```

pip3 install python-telegram-bot

```

**Comment by nlhomme** [comment]
> > > Return is printed when runing the container with
> > > # docker run -it nlhomme/pytgvoip:latest
> > > Traceback (most recent call last):
> > > File "/root/tgcall.py", line 10, in 
> > > ```
> > > from telegram.client import Telegram
> > > ```
> > > 
> > > 
> > > ModuleNotFoundError: No module named 'telegram'
> > 
> > 
> > We should see [this](https://stackoverflow.com/questions/45382698/although-i-install-python-telegram-bot-error-of-no-module-named-telegram)
> 
> I think the solution is
> 
> ```
> 
> pip3 install python-telegram-bot
> ```

Added on [commit 32361e3](https://github.com/nlhomme/pytgvoip/commit/32361e39509c1b7d0830578b304d3de3ffe48566)

**Comment by nlhomme** [comment]
Build passed, issue gone but other issue appeared.
Closing the issue
