### ISSUE TITLE
Database encryption key

### ISSUE THREAD

**Issue by Yapele** [nlhomme/pytgvoip#7]
@nlhomme I am trying to obtain TDLib database key but i am not winning. I tried even the generator using Debian 10.

**Comment by nlhomme** [comment]
I don't know what generator you're talking about.
You're also not supposed to obtain TDLib database key since you have to generate it, as I said on the README.md:
```
python3 tgcall.py api_id api_hash phone_number user_id dbkeyofyourchoice
```
`dbkeyofyourchoice` can be `wi6kagu9Faenai2eepaebeB6`, `jackbauer` or anything you want
